### ISSUE TITLE
Adding this to KoolKits?

### ISSUE THREAD

**Issue by TomGranot** [keyval-dev/opentelemetry-go-instrumentation#4]
Hiya!

I've caught this repo from Observability News by [Michael Hasuenblas](https://twitter.com/mhausenblas?utm_source=o11y.news&utm_medium=email) - great stuff:) 

I wonder, since this requires 0 code changes, whether it will be a good fit to bundle into our OSS project KoolKits.

We have docker debug images specifically geared towards debugging applications written in a specific language - you can check out the project [here](https://github.com/lightrun-platform/koolkits).

This might fit into our Go KoolKit. 

Your comments much appreciated @edeNFed :)

**Comment by edeNFed** [comment]
Hi @TomGranot,
KoolKit looks like a really cool project!
Adding auto instrumentation to the Go image should be pretty easy, probably just copying the binary from this Dockerfile:
https://github.com/keyval-dev/opentelemetry-go-instrumentation/blob/master/Dockerfile

Will be happy to open a PR if you think it's a good idea.

**Comment by TomGranot** [comment]
@edeNFed Please do! That would be awesome.

If you can also add it to the README for the Go KoolKit with a quick explainer I'll appreciate that too:)

**Comment by edeNFed** [comment]
Sure no problem, I'll let you know once I finished adding to KoolKit so we can update the README file.

**Comment by TomGranot** [comment]
@edeNFed Dope. Talk soon!

**Comment by edeNFed** [comment]
Hi @TomGranot,
I tried to include the project in the KoolKit container but I had a few issues.
The main problem is that in order for this instrumentation to run we need to add privileges to the pod, for example:
```yaml
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
          volumeMounts:
            - mountPath: /sys/kernel/debug
              name: kernel-debug
```

I could not find a flag in `kubectl debug` which allows adding securtityContext or volume mounts.
I do see that `kubectl debug` has a "node mode" which allows the creation of pods that runs with enhanced privileges.
What do you think? Should I try to use this mode or do you have other suggestions?
