### ISSUE TITLE
Go service is stuck in crashloopbackoff after instrumentation. Am I doing something wrong?

### ISSUE THREAD

**Issue by mayanksingh2298** [keyval-dev/opentelemetry-go-instrumentation#57]
# Expected Behavior
```
kubectl get pods -n atlas
pod/go-service-8c86cf596-5rbpc                 2/2     Running
```
# Actual Behavior
```
kubectl get pods -n atlas
pod/go-service-8c86cf596-5rbpc                 1/2     CrashLoopBackOff
```
# Steps to Reproduce the Problem
Here's my manifest file relevant for go:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-service
  name: go-service
  namespace: atlas
spec:
  ports:
  - port: 30002
    protocol: TCP
    targetPort: 30002
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30002
  selector:
    app: go-service
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-service
  name: go-service
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-service
  strategy: {}
  template:
    metadata:
      labels:
        app: go-service
    spec:
      shareProcessNamespace: true
      initContainers:
        - name: copy-launcher
          image: keyval/launcher:v0.1
          command:
            - cp
            - -a
            - /kv-launcher/.
            - /odigos-launcher/
          volumeMounts:
            - name: launcherdir
              mountPath: /odigos-launcher
      containers:
        - args:
          - go-service
          image: dev0zklabs/atlas-demo-microservice:go-service
          name: go-service
          command:
            - /odigos-launcher/launch
            - /root/go-service
          volumeMounts:
            - mountPath: /odigos-launcher
              name: launcherdir
          ports:
          - containerPort: 30002
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: envs-config
          resources: {}
        - name: emojivoto-emoji-instrumentation
          image: keyval/otel-go-agent:v0.6.4
          env:
            - name: OTEL_TARGET_EXE
              value: /root/go-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "jaeger:4317"
            - name: OTEL_SERVICE_NAME
              value: "go-service"
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
          volumeMounts:
            - mountPath: /sys/kernel/debug
              name: kernel-debug
      volumes:
        - name: launcherdir
          emptyDir: {}
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
status: {}
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.8-eks-ec5523e", GitCommit:"83fe90de881ffe7450876d204ccdc37a0f95bda3", GitTreeState:"clean", BuildDate:"2023-03-20T21:32:06Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
Ubuntu 22.04.2 LTS
5.19.0-1022-aws
  ```
